# Generated by Django 4.0 on 2021-12-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearRange', models.CharField(max_length=220)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
