# Generated by Django 4.0 on 2021-12-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_clinicaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=220)),
                ('refs', models.IntegerField()),
                ('trials', models.IntegerField()),
            ],
        ),
    ]
